name: dart_dev
version: 3.6.4
description: Centralized tooling for Dart projects. Consistent interface across projects. Easily configurable.
homepage: https://github.com/Workiva/dart_dev

environment:
 sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  args: ^2.0.0
  async: ^2.3.0
  build_runner: ^1.7.0
  completion: ^1.0.0
  glob: ^2.0.0
  io: ^0.3.3
  logging: ^1.0.0
  path: ^1.6.2
  pedantic: ^1.7.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  stack_trace: ^1.9.3
  yaml: ^3.0.0

dev_dependencies:
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  matcher: ^0.12.5
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^1.0.4
